; PlatformIO Project Configuration File
; Day 6 - Exercise 17: 32-Bit Cross-Compilation Environment

[platformio]
default_envs = esp32dev ; Sets the 32-bit chip as the default compilation target

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.15
    arduino-libraries/Servo@^1.2.2
    deanisme/SevSeg@^3.7.0

[env:esp32dev]
platform = espressif32@^6.5.0           ; Industrial Expressif 32-bit platform core
board = esp32dev                        ; Generic ESP32 Development Board definition
framework = arduino                     ; Arduino abstraction layer for 32-bit registers
monitor_speed = 115200                  ; Native high-speed UART baud rate for ESP32
lib_deps =
    adafruit/DHT sensor library@^1.4.6  ; Porting the exact same climate driver
